sonar.projectKey=Csontikka_microlink
sonar.organization=csontikka
sonar.projectName=microlink

sonar.sources=components/microlink
sonar.inclusions=**/*.c,**/*.h
sonar.exclusions=**/build/**,**/examples/**

sonar.sourceEncoding=UTF-8
